### PR TITLE
Bump jersey client

### PR DESCRIPTION
**Pull request by chadworth**

### CODE REVIEW

**Comment by harlow** [comment]
Looks good. thanks for updating 👍

**Comment by chadworth** [comment]
@harlow would it be possible to release a new version? i'd like to see if this fixes https://github.com/clearbit/clearbit-java/issues/9

**Comment by harlow** [comment]
yeah for sure... will need to dig up my notes on how to do it again

**Comment by chadworth** [comment]
Now that you've gone through all the initial setup trouble of getting the `pom.xml` file right in this repo, it should be as simple as:

    mvn release:prepare
    mvn release:perform

You'll need to make sure to do it on the machine with your gpg key and you made need to visit https://oss.sonatype.org/index.html#welcome for a portion of the release process.

**Comment by harlow** [comment]
@chadworth done. 0.6 has been released.

**Pull request merged**
